### ISSUE TITLE
오류로 정렬 기능 작동하지 않음

### ISSUE THREAD

**Issue by saschanaz** [foriequal0/naver-webtoon-helper#19]
https://github.com/foriequal0/naver-webtoon-helper/blob/76eba346d7024baec936138b68e2386f2433a518/src/rearrange.ts#L35-L38

이 부분에서 `states`에 `thumbs`의 일부 항목만이 저장됩니다. 따라서

https://github.com/foriequal0/naver-webtoon-helper/blob/76eba346d7024baec936138b68e2386f2433a518/src/rearrange.ts#L56

에서 "state is undefined" 오류가 생깁니다.

**Comment by foriequal0** [comment]
그거 이상하네요.
`getTitleStates` 가 리턴하는 `states` 는 인자로 받은 `titleId` 를 모두 포함하게 되어있습니다. storage 에 없으면 default 라도 만들어서 제공합니다.
`thumbs` 의 `titleId` 를 모두 포함하는 `states` 에 `for(const thumb of thumbs) states[thumb.titleId]` 가 undefined 가 나오는 상황이 잘 생각이 안납니다.
혹시 어느 페이지에서 그런 현상이 벌어지나요?

**Comment by saschanaz** [comment]
https://comic.naver.com/webtoon/weekday 및 각 요일별 페이지에서 일어납니다. 예외적으로 월요일 페이지만 오류가 없는데 차이를 모르겠습니다.

**Comment by foriequal0** [comment]
아 저도 발생하네요

**Comment by foriequal0** [comment]
세상에 제가 저장할때 titleId 가 실수로 안들어간 모양입니다.

**Comment by foriequal0** [comment]
v0.2.1 에서 고쳤습니다.
