### ISSUE TITLE
요일별 페이지에서 분류가 작동하지 않음

### ISSUE THREAD

**Issue by saschanaz** [foriequal0/naver-webtoon-helper#25]
전체 웹툰 페이지에서는 작동하는데 요일별 페이지에서는 작동하지 않습니다. 처음엔 됐던 것 같은데 뭔가 바뀌었을지도 모르겠네요.

**Comment by foriequal0** [comment]
https://discourse.mozilla.org/t/uploading-a-new-addon-or-updating-the-existing-addon-stucks-at-validating/113089/14 이 이슈로 새 버전 업로드가 진행되고 있지 않습니다. 이슈 해결되면 업로드 재시도 해보겠습니다.

**Comment by saschanaz** [comment]
스토어 업로드를 했었나요?!

**Comment by foriequal0** [comment]
스토어 배포는 아니고 셀프호스팅 배포긴 한데 서명때문에 업로드 했었습니다.

**Comment by saschanaz** [comment]
음... 여전히 작동하지 않습니다. 얼핏 보기로 regex가 잘못되지 않았나 싶어요

https://github.com/foriequal0/naver-webtoon-helper/blob/614ba5d90fd8d5b3ca2364fafc918ff892afffe4/src/main.ts#L27-L28

실제 URL은 https://comic.naver.com/webtoon?tab=tue 같이 생겼으니 `/\/webtoon\?/`이 되어야 할 것 같습니다
