### ISSUE TITLE
빌드시 npm run 명령어 사용

### ISSUE THREAD

**Issue by saschanaz** [foriequal0/naver-webtoon-helper#7]
빌드할 때 `npm run build` 로 빌드가 되면 좋겠습니다. gnu make도 설치돼 있으니 지금 구성도 저한테는 안될 건 없는데 이왕 npm을 사용하는 겸 하나만 쓰는 게 더 좋지 않을까 싶어요 😄

**Comment by foriequal0** [comment]
저는 Make쪽을 선호하는데 둘 다 하죠 :)
